--ÉfÅ[É^ëçêî
/*
SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL ;
*/

SELECT MIN(DEAL_YMD),MAX(DEAL_YMD),MAX(LENGTH(DEAL_YMD)),MIN(LENGTH(DEAL_YMD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(DEAL_HOUR),MAX(DEAL_HOUR),MAX(LENGTH(DEAL_HOUR)),MIN(LENGTH(DEAL_HOUR))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(STORECD),MAX(STORECD),MAX(LENGTH(STORECD)),MIN(LENGTH(STORECD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(STORENAME),MAX(STORENAME),MAX(LENGTH(STORENAME)),MIN(LENGTH(STORENAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(DIVISIONCD),MAX(DIVISIONCD),MAX(LENGTH(DIVISIONCD)),MIN(LENGTH(DIVISIONCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(DIVISIONNAME),MAX(DIVISIONNAME),MAX(LENGTH(STORENAME)),MIN(LENGTH(STORENAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(LINECD),MAX(LINECD),MAX(LENGTH(LINECD)),MIN(LENGTH(LINECD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(LINENAME),MAX(LINENAME),MAX(LENGTH(LINENAME)),MIN(LENGTH(LINENAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(DEPARTMENTCD),MAX(DEPARTMENTCD),MAX(LENGTH(DEPARTMENTCD)),MIN(LENGTH(DEPARTMENTCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(DEPARTMENTNAME),MAX(DEPARTMENTNAME),MAX(LENGTH(DEPARTMENTNAME)),MIN(LENGTH(DEPARTMENTNAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(CATEGORYCD),MAX(CATEGORYCD),MAX(LENGTH(CATEGORYCD)),MIN(LENGTH(CATEGORYCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(CATEGORYNAME),MAX(CATEGORYNAME),MAX(LENGTH(CATEGORYNAME)),MIN(LENGTH(CATEGORYNAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SUBCATEGORYCD),MAX(SUBCATEGORYCD),MAX(LENGTH(SUBCATEGORYCD)),MIN(LENGTH(SUBCATEGORYCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SUBCATEGORYNAME),MAX(SUBCATEGORYNAME),MAX(LENGTH(SUBCATEGORYNAME)),MIN(LENGTH(SUBCATEGORYNAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SEGMENTCD),MAX(SEGMENTCD),MAX(LENGTH(SEGMENTCD)),MIN(LENGTH(SEGMENTCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SEGMENTNAME),MAX(SEGMENTNAME),MAX(LENGTH(SEGMENTNAME)),MIN(LENGTH(SEGMENTNAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SUBSEGMENTCD),MAX(SUBSEGMENTCD),MAX(LENGTH(SUBSEGMENTCD)),MIN(LENGTH(SUBSEGMENTCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SUBSEGMENTNAME),MAX(SUBSEGMENTNAME),MAX(LENGTH(SUBSEGMENTNAME)),MIN(LENGTH(SUBSEGMENTNAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(JANCD),MAX(JANCD),MAX(LENGTH(JANCD)),MIN(LENGTH(JANCD))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(PRODUCTNAME),MAX(PRODUCTNAME),MAX(LENGTH(PRODUCTNAME)),MIN(LENGTH(PRODUCTNAME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SPECIFICATION),MAX(SPECIFICATION),MAX(LENGTH(SPECIFICATION)),MIN(LENGTH(SPECIFICATION))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(MAKER),MAX(MAKER),MAX(LENGTH(MAKER)),MIN(LENGTH(MAKER))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(MEMBERID),MAX(MEMBERID),MAX(LENGTH(MEMBERID)),MIN(LENGTH(MEMBERID))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SEX),MAX(SEX),MAX(LENGTH(SEX)),MIN(LENGTH(SEX))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(AGERANGE),MAX(AGERANGE),MAX(LENGTH(AGERANGE)),MIN(LENGTH(AGERANGE))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(VISITDISTANCELEKM),MAX(VISITDISTANCELEKM),MAX(LENGTH(VISITDISTANCELEKM)),MIN(LENGTH(VISITDISTANCELEKM))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(UNITPRICE),MAX(UNITPRICE),MAX(LENGTH(UNITPRICE)),MIN(LENGTH(UNITPRICE))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SALESVOLUME),MAX(SALESVOLUME),MAX(LENGTH(SALESVOLUME)),MIN(LENGTH(SALESVOLUME))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(SALESTAXINCLUDED),MAX(SALESTAXINCLUDED),MAX(LENGTH(SALESTAXINCLUDED)),MIN(LENGTH(SALESTAXINCLUDED))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(ARGUMENTAMOUNT),MAX(ARGUMENTAMOUNT),MAX(LENGTH(ARGUMENTAMOUNT)),MIN(LENGTH(ARGUMENTAMOUNT))
FROM JDMC2020.JDMC2020_RETAIL ;

SELECT MIN(DINCOUNTAMOUNT),MAX(DINCOUNTAMOUNT),MAX(LENGTH(DINCOUNTAMOUNT)),MIN(LENGTH(DINCOUNTAMOUNT))
FROM JDMC2020.JDMC2020_RETAIL ;
