--ÉfÅ[É^ëçêî
/*
SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL ;
*/

SELECT MIN(DEAL_YMD),MAX(DEAL_YMD),MAX(LENGTH(DEAL_YMD)),MIN(LENGTH(DEAL_YMD))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY;

SELECT MIN(DEAL_HOUR),MAX(DEAL_HOUR),MAX(LENGTH(DEAL_HOUR)),MIN(LENGTH(DEAL_HOUR))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(STORECD),MAX(STORECD),MAX(LENGTH(STORECD)),MIN(LENGTH(STORECD))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(STORENAME),MAX(STORENAME),MAX(LENGTH(STORENAME)),MIN(LENGTH(STORENAME))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(LOCALPRESSURE),MAX(LOCALPRESSURE),MAX(LENGTH(LOCALPRESSURE)),MIN(LENGTH(LOCALPRESSURE))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(SEALEVELPRESSURE),MAX(SEALEVELPRESSURE),MAX(LENGTH(SEALEVELPRESSURE)),MIN(LENGTH(SEALEVELPRESSURE))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(PRECIPITATIONAMOUNT),MAX(PRECIPITATIONAMOUNT),MAX(LENGTH(PRECIPITATIONAMOUNT)),MIN(LENGTH(PRECIPITATIONAMOUNT))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(TEMPERATURE),MAX(TEMPERATURE),MAX(LENGTH(TEMPERATURE)),MIN(LENGTH(TEMPERATURE))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(DEWPOINTTEMPERATURE),MAX(DEWPOINTTEMPERATURE),MAX(LENGTH(DEWPOINTTEMPERATURE)),MIN(LENGTH(DEWPOINTTEMPERATURE))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(VAPORPRESSURE),MAX(VAPORPRESSURE),MAX(LENGTH(VAPORPRESSURE)),MIN(LENGTH(VAPORPRESSURE))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(HUMIDITY),MAX(HUMIDITY),MAX(LENGTH(HUMIDITY)),MIN(LENGTH(HUMIDITY))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(WINDSPEED),MAX(WINDSPEED),MAX(LENGTH(WINDSPEED)),MIN(LENGTH(WINDSPEED))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(WINDDIRECTION),MAX(WINDDIRECTION),MAX(LENGTH(WINDDIRECTION)),MIN(LENGTH(WINDDIRECTION))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(SUNLIGHTHOURS),MAX(SUNLIGHTHOURS),MAX(LENGTH(SUNLIGHTHOURS)),MIN(LENGTH(SUNLIGHTHOURS))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(TOTALSOLARRADIATION),MAX(TOTALSOLARRADIATION),MAX(LENGTH(TOTALSOLARRADIATION)),MIN(LENGTH(TOTALSOLARRADIATION))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(SNOWFALL),MAX(SNOWFALL),MAX(LENGTH(SNOWFALL)),MIN(LENGTH(SNOWFALL))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(SNOWCOVER),MAX(SNOWCOVER),MAX(LENGTH(SNOWCOVER)),MIN(LENGTH(SNOWCOVER))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(WEATHER),MAX(WEATHER),MAX(LENGTH(WEATHER)),MIN(LENGTH(WEATHER))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(CLOUDCOVER),MAX(CLOUDCOVER),MAX(LENGTH(CLOUDCOVER)),MIN(LENGTH(CLOUDCOVER))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;

SELECT MIN(VISIBILITY),MAX(VISIBILITY),MAX(LENGTH(VISIBILITY)),MIN(LENGTH(VISIBILITY))
FROM JDMC2020.JDMC2020_WEATHER_HOURLY ;
