--ÉfÅ[É^ëçêî
/*
weather daily null check
*/

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE DEAL_YMD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE STORECD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE STORENAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE AVERAGETEMPERATURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE HIGHESTTEMPERATURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE LOWESTTEMPERATURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE TOTALPRECIPITATION IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE MAXIMUMHOURLYPRECIPITATION IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE SUNSHINEHOURS IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE TOTALSNOWFALL IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE AVERAGEWINDSPEED IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE MAXIMUMWINDSPEED IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE MAXIMUMWINDSPEEDDIRECTION IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE AVERAGEHUMIDITY IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE WEATHEROVERVIEWDAYTIME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
WHERE WEATHEROVERVIEWNIGHT IS NOT NULL ;

