--ÉfÅ[É^ëçêî
/*
SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL ;
*/

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DEAL_YMD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DEAL_HOUR IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE STORECD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE STORENAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DIVISIONCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DIVISIONNAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE LINECD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE LINENAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DEPARTMENTCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DEPARTMENTNAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE CATEGORYCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE CATEGORYNAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SUBCATEGORYCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SUBCATEGORYNAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SEGMENTCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SEGMENTNAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SUBSEGMENTCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE JANCD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE PRODUCTNAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SPECIFICATION IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE MAKER IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE MEMBERID IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SEX IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE AGERANGE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE VISITDISTANCELEKM  IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE UNITPRICE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SALESVOLUME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE SALESTAXINCLUDED IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE ARGUMENTAMOUNT IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE DINCOUNTAMOUNT IS NOT NULL ;
