--ÉfÅ[É^ëçêî
/*
SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL ;
*/

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE DEAL_YMD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE DEAL_HOUR  IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE STORECD IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE STORENAME IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE LOCALPRESSURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE SEALEVELPRESSURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE PRECIPITATIONAMOUNT IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE TEMPERATURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE DEWPOINTTEMPERATURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE VAPORPRESSURE IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE HUMIDITY IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE WINDSPEED IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE WINDDIRECTION IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE SUNLIGHTHOURS IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE TOTALSOLARRADIATION IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE SNOWFALL IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE SNOWCOVER IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE WEATHER IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE CLOUDCOVER IS NOT NULL ;

SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_HOURLY
WHERE VISIBILITY IS NOT NULL ;

