
SELECT *
FROM JDMC2020.JDMC2020_WEATHER_DAILY 
WHERE AVERAGETEMPERATURE IS NULL ;

SELECT *
FROM JDMC2020.JDMC2020_WEATHER_DAILY 
WHERE STORENAME = '' ;

SELECT DISTINCT 
FROM JDMC2020.JDMC2020_WEATHER_DAILY 
WHERE STORENAME = '' ;
