/*
unique check weather daily
*/

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DEAL_YMD
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  STORECD
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  STORENAME 
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  AVERAGETEMPERATURE
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  HIGHESTTEMPERATURE
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  LOWESTTEMPERATURE
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

	SELECT COUNT(*)
	FROM (
		SELECT DISTINCT  TOTALPRECIPITATION
		FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  MAXIMUMHOURLYPRECIPITATION
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SUNSHINEHOURS
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  TOTALSNOWFALL
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  AVERAGEWINDSPEED
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  MAXIMUMWINDSPEED
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  MAXIMUMWINDSPEEDDIRECTION
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  AVERAGEHUMIDITY
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  WEATHEROVERVIEWDAYTIME
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  WEATHEROVERVIEWNIGHT
	FROM JDMC2020.JDMC2020_WEATHER_DAILY) ;





