--データ総数
/*
SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_RETAIL ;
*/

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DEAL_YMD
	FROM JDMC2020.JDMC2020_RETAIL) ;


SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DEAL_HOUR
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  STORECD
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  STORENAME 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DIVISIONCD
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DIVISIONNAME 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  LINECD 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  LINENAME 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DEPARTMENTCD 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DEPARTMENTNAME 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  CATEGORYCD  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  CATEGORYNAME  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SUBCATEGORYCD  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SUBCATEGORYNAME  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SUBCATEGORYNAME  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SEGMENTCD  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SEGMENTNAME  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SUBSEGMENTCD  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SUBSEGMENTNAME  
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  JANCD 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  PRODUCTNAME 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SPECIFICATION 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  MAKER 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  MEMBERID 
	FROM JDMC2020.JDMC2020_RETAIL) ;

--会員のユニーク数
SELECT COUNT(DISTINCT MEMBERID) 
FROM JDMC2020.JDMC2020_RETAIL
WHERE MEMBERID <> '0'
;


SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SEX 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  AGERANGE 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  VISITDISTANCELEKM 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  UNITPRICE 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SALESVOLUME 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  SALESTAXINCLUDED 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  ARGUMENTAMOUNT 
	FROM JDMC2020.JDMC2020_RETAIL) ;

SELECT COUNT(*)
FROM (
	SELECT DISTINCT  DINCOUNTAMOUNT 
	FROM JDMC2020.JDMC2020_RETAIL) ;

