--ÉfÅ[É^ëçêî
SELECT COUNT(*) 
FROM JDMC2020.JDMC2020_WEATHER_DAILY
LIMIT 10 ;

SELECT *
FROM JDMC2020.JDMC2020_WEATHER_DAILY
LIMIT 10 ;


SELECT MIN(DEAL_YMD),MAX(DEAL_YMD),MAX(LENGTH(DEAL_YMD)),MIN(LENGTH(DEAL_YMD))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(STORECD),MAX(STORECD),MAX(LENGTH(STORECD)),MIN(LENGTH(STORECD))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(STORENAME),MAX(STORENAME),MAX(LENGTH(STORENAME)),MIN(LENGTH(STORENAME))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(AVERAGETEMPERATURE),MAX(AVERAGETEMPERATURE),MAX(LENGTH(AVERAGETEMPERATURE)),MIN(LENGTH(AVERAGETEMPERATURE))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(HIGHESTTEMPERATURE),MAX(HIGHESTTEMPERATURE),MAX(LENGTH(HIGHESTTEMPERATURE)),MIN(LENGTH(HIGHESTTEMPERATURE))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(LOWESTTEMPERATURE),MAX(LOWESTTEMPERATURE),MAX(LENGTH(LOWESTTEMPERATURE)),MIN(LENGTH(LOWESTTEMPERATURE))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(TOTALPRECIPITATION),MAX(TOTALPRECIPITATION),MAX(LENGTH(TOTALPRECIPITATION)),MIN(LENGTH(TOTALPRECIPITATION))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(MAXIMUMHOURLYPRECIPITATION),MAX(MAXIMUMHOURLYPRECIPITATION),MAX(LENGTH(MAXIMUMHOURLYPRECIPITATION)),MIN(LENGTH(MAXIMUMHOURLYPRECIPITATION))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(SUNSHINEHOURS),MAX(SUNSHINEHOURS),MAX(LENGTH(SUNSHINEHOURS)),MIN(LENGTH(SUNSHINEHOURS))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(TOTALSNOWFALL),MAX(TOTALSNOWFALL),MAX(LENGTH(TOTALSNOWFALL)),MIN(LENGTH(TOTALSNOWFALL))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(AVERAGEWINDSPEED),MAX(AVERAGEWINDSPEED),MAX(LENGTH(AVERAGEWINDSPEED)),MIN(LENGTH(AVERAGEWINDSPEED))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(MAXIMUMWINDSPEED),MAX(MAXIMUMWINDSPEED),MAX(LENGTH(MAXIMUMWINDSPEED)),MIN(LENGTH(MAXIMUMWINDSPEED))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(MAXIMUMWINDSPEEDDIRECTION),MAX(MAXIMUMWINDSPEEDDIRECTION),MAX(LENGTH(MAXIMUMWINDSPEEDDIRECTION)),MIN(LENGTH(MAXIMUMWINDSPEEDDIRECTION))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(AVERAGEHUMIDITY),MAX(AVERAGEHUMIDITY),MAX(LENGTH(AVERAGEHUMIDITY)),MIN(LENGTH(AVERAGEHUMIDITY))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(WEATHEROVERVIEWDAYTIME),MAX(WEATHEROVERVIEWDAYTIME),MAX(LENGTH(WEATHEROVERVIEWDAYTIME)),MIN(LENGTH(WEATHEROVERVIEWDAYTIME))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;

SELECT MIN(WEATHEROVERVIEWNIGHT),MAX(WEATHEROVERVIEWNIGHT),MAX(LENGTH(WEATHEROVERVIEWNIGHT)),MIN(LENGTH(WEATHEROVERVIEWNIGHT))
FROM JDMC2020.JDMC2020_WEATHER_DAILY ;


